Moved Color.getRaylibColor() to RaylibUtil.getRaylibColor()
OrbitalEngine/Orbital pull request #21
Opened 2022-10-05 14:36 UTC by andreaevolo

2022-10-06 01:20 UTC, YeffyCodeGit commented
Thanks for contributing to Orbital! I will review and merge this pull request in a few hours, but busy right now :D

2022-10-06 07:59 UTC, YeffyCodeGit requested changes
Looks good, but you haven't changed the uses of the class version of the function to the RaylibUtil version.

2022-10-06 12:37 UTC, andreaevolo commented
@YeffyCodeGit My bad. I'll fix it right now.

2022-10-06 13:47 UTC, Yeffian requested changes
The function should take in a parameter for the `Color` to turn into a Raylib color, your current code would not compile as the r, g, b and a variables are undefined. Please make sure your code code actually compiles before making a push.

2022-10-06 14:30 UTC, andreaevolo commented
![javara](https://user-images.githubusercontent.com/37835057/194339803-9cb7d42a-2b19-4f59-aaab-e00ab924b06f.PNG)
![Cattujaavaa](https://user-images.githubusercontent.com/37835057/194340119-659197a7-e8f8-450b-a398-e64840cacd0c.PNG)
That was the problem right? ( I'll fix all the other methods too in the Randerer class ). @YeffyCodeGit

2022-10-06 15:01 UTC, andreaevolo commented
![Cat1](https://user-images.githubusercontent.com/37835057/194346133-58984735-d675-447f-a0da-4ad5bf0d603a.PNG)
![Cat2](https://user-images.githubusercontent.com/37835057/194346858-3094983a-e3d6-4f9e-b66b-8f170d8255b0.PNG)
Is this the problem you were talking about? If yes I'll fix all the methods inside the renderer class.

But then I need to fix this. 
![Cattura4](https://user-images.githubusercontent.com/37835057/194347835-c70f5de7-06f2-4e05-a954-529071d23081.PNG)

2022-10-07 10:02 UTC, YeffyCodeGit requested changes

2022-10-07 10:02 UTC, Yeffian commented on src/main/java/dev/yeff/orbital/graphics/Renderer.java
> +        DrawCircleV(RaylibUtil.getAsRaylibVec2(pos), radius, RaylibUtil.getRaylibColor(color));
The function definition does not take a `Color` object, so this won't compile again. Please make sure the code your submitting is correct.

Again, the function needs to take a `Color` parameter, and the r, g, b and a values need to come from the parameter.

2022-10-07 11:03 UTC, andreaevolo commented
@YeffyCodeGit I messed up something with git because I did change the function definition but my changes weren't reflected in the commit. Sorry for the inconvenient.

2022-10-07 11:13 UTC, YeffyCodeGit commented
In that case, could you push the changes again?

2022-10-07 11:15 UTC, andreaevolo commented
![Cattura](https://user-images.githubusercontent.com/37835057/194540732-914ddbcb-89b4-40b5-8343-37a31ea9c7d3.PNG)
that's how I changed the method definition in my local code.

2022-10-07 11:16 UTC, andreaevolo commented
@YeffyCodeGit Yeah I'll check what went wrong and send a push again.

2022-10-08 00:40 UTC, YeffyCodeGit commented
LGTM!

2022-10-08 00:41 UTC, merged